package com.gitranker.api.global.logging;

public enum EventType {
    REQUEST,
    RESPONSE,
    SUCCESS,
    FAILURE,
    SKIP,
    RETRY,
    THRESHOLD,
    USER_REGISTERED,
    USER_REFRESHED,
    TIER_CHANGED,
    SCORE_UPDATED,
    BATCH_STARTED,
    BATCH_PROGRESS,
    BATCH_COMPLETED,
    BATCH_ITEM_FAILED,
    API_CALLED,
    API_SUCCEEDED,
    API_FAILED,
    API_RATE_THRESHOLD,
    AUTH_SUCCESS,
    AUTH_FAILED,
    TOKEN_ISSUED,
    TOKEN_REFRESHED
}
